
language: node_js
node_js: node

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - public/static

before_script:
  - npm i -g gatsby-cli
  - yarn

script:
  - travis_wait 30 gatsby build

before_deploy:
  - npm install netlify-cli -g
  - npm run build

# deploy:
#   provider: script
#   script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public
#   skip_cleanup: true
#   on:
#     branch: master
